/**
 * Centralized API endpoints matching Gateway YARP routes.
 * Base URL is set in apiClient (NEXT_PUBLIC_API_URL).
 */
export const API = {
  auth: {
    register: "/auth/register",
    registerInvited: "/auth/register-invited",
    login: "/auth/login",
    googleLogin: "/auth/google-login",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    me: "/auth/me",
    changePassword: "/auth/change-password",
    settings: "/auth/settings",
  },
  voiceProfiles: {
    list: "/auth/voice-profiles",
    create: "/auth/voice-profiles",
    delete: (id: string) => `/auth/voice-profiles/${id}`,
    catalog: "/auth/voice-profiles/catalog",
    preferredVoice: "/auth/voice-profiles/preferred-voice",
  },
  translationRooms: {
    create: "/translation-rooms",
    list: "/translation-rooms",
    history: "/translation-rooms/history",
    join: "/translation-rooms/join",
    get: (id: string) => `/translation-rooms/${id}`,
    participants: (id: string) => `/translation-rooms/${id}/participants`,
    invitations: (id: string) => `/translation-rooms/${id}/invitations`,
    participantAudio: (id: string, participantId: string) =>
      `/translation-rooms/${id}/participants/${participantId}/audio`,
    admitParticipant: (id: string, participantId: string) =>
      `/translation-rooms/${id}/participants/${participantId}/admit`,
    kickParticipant: (id: string, participantId: string) =>
      `/translation-rooms/${id}/participants/${participantId}/kick`,
    leave: (id: string) => `/translation-rooms/${id}/participants/me/leave`,
    start: (id: string) => `/translation-rooms/${id}/start`,
    pause: (id: string) => `/translation-rooms/${id}/pause`,
    /** Start Translation. `/start` only opens the room — see ResumeTranslationRoomAsync. */
    resume: (id: string) => `/translation-rooms/${id}/resume`,
    /** Stop Translation and leave the meeting (and its transcript) running. Not `/pause`. */
    stopTranslation: (id: string) => `/translation-rooms/${id}/translation/stop`,
    end: (id: string) => `/translation-rooms/${id}/end`,
    cancel: (id: string) => `/translation-rooms/${id}/cancel`,
    artifacts: (id: string) => `/translation-rooms/${id}/artifacts`,
    settings: (id: string) => `/translation-rooms/${id}/settings`,
    feedbackState: (id: string) => `/translation-rooms/${id}/feedback/me`,
    feedback: (id: string) => `/translation-rooms/${id}/feedback`,
    preflight: (roomCode: string) => `/translation-rooms/preflight/${roomCode}`,
    generateAudioRoutes: (id: string) => `/translation-rooms/${id}/audio-routes/generate`,
    voiceCloneConsent: (id: string) => `/translation-rooms/${id}/audio-routes/voice-clone-consent`,
    calendarIcs: (id: string) => `/translation-rooms/${id}/calendar.ics`,
    sessions: (id: string) => `/translation-rooms/${id}/sessions`,
  },
  // WT-327: the recurring BOOKING, not its meetings. Creating one goes through
  // translationRooms.create with a `recurrence` block; these two are about the series itself.
  translationRoomSeries: {
    get: (id: string) => `/translation-room-series/${id}`,
    update: (id: string) => `/translation-room-series/${id}`,
    cancel: (id: string) => `/translation-room-series/${id}/cancel`,
  },
  roomArtifacts: {
    download: (id: string) => `/room-artifacts/${id}/download`,
    consent: (id: string) => `/room-artifacts/${id}/consent`,
    regenerateSummary: (roomId: string) =>
      `/room-artifacts/rooms/${roomId}/summary/regenerate`,
  },
  transcripts: {
    start: "/transcripts",
    get: (id: string) => `/transcripts/${id}`,
    byRoom: (translationRoomId: string) => `/transcripts/by-room/${translationRoomId}`,
    segments: (id: string) => `/transcripts/${id}/segments`,
    translations: (id: string) => `/transcripts/${id}/translations`,
    exports: (id: string) => `/transcripts/${id}/exports`,
    exportDownload: (id: string, exportId: string) => `/transcripts/${id}/exports/${exportId}/download`,
    correctSegment: (id: string, segmentId: string) => `/transcripts/${id}/segments/${segmentId}/correct`,
    corrections: (id: string, segmentId: string) => `/transcripts/${id}/segments/${segmentId}/corrections`,
    audio: (id: string) => `/transcripts/${id}/audio`,
    finalize: (id: string) => `/transcripts/${id}/finalize`,
  },
  notifications: {
    base: "/notifications",
    preferences: "/notifications/preferences",
    read: (id: string) => `/notifications/${id}/read`,
    readAll: "/notifications/read-all",
    adminBase: "/admin/notifications",
  },
  meetings: {
    join: (translationRoomId: string) => `/meetings/rooms/${translationRoomId}/join`,
    triggerAi: (translationRoomId: string) => `/meetings/rooms/${translationRoomId}/trigger-ai`,
    chatList: (roomId: string) => `/meetings/rooms/${roomId}/chat`,
    chatSend: (roomId: string) => `/meetings/rooms/${roomId}/chat`,
    chatSendFile: (roomId: string) => `/meetings/rooms/${roomId}/chat/files`,
    chatDownload: (roomId: string, messageId: string) =>
      `/meetings/rooms/${roomId}/chat/files/${messageId}/download`,
    chatTranslate: (roomId: string, messageId: string) => `/meetings/rooms/${roomId}/chat/${messageId}/translate`,
    chatModerate: (roomId: string, messageId: string) => `/meetings/rooms/${roomId}/chat/${messageId}/moderate`,
    rejectParticipant: (roomId: string, participantId: string) => `/meetings/rooms/${roomId}/participants/${participantId}/reject`,
    transferHost: (roomId: string, newHostId: string) => `/meetings/rooms/${roomId}/transfer-host/${newHostId}`,
    muteParticipant: (roomId: string, participantId: string) =>
      `/meetings/rooms/${roomId}/participants/${participantId}/mute`,
    kickParticipant: (roomId: string, participantId: string) => `/meetings/rooms/${roomId}/participants/${participantId}/kick`,
    endMeeting: (roomId: string) => `/meetings/rooms/${roomId}/end`,
    setLock: (roomId: string) => `/meetings/rooms/${roomId}/lock`,
    setMuteOnEntry: (roomId: string) => `/meetings/rooms/${roomId}/mute-on-entry`,
    setRecording: (roomId: string) => `/meetings/rooms/${roomId}/recording`,
    pollsList: (roomId: string) => `/meetings/rooms/${roomId}/polls`,
    pollsCreate: (roomId: string) => `/meetings/rooms/${roomId}/polls`,
    pollsVote: (roomId: string, pollId: string) => `/meetings/rooms/${roomId}/polls/${pollId}/vote`,
    pollsClose: (roomId: string, pollId: string) => `/meetings/rooms/${roomId}/polls/${pollId}/close`,
    questionsList: (roomId: string) => `/meetings/rooms/${roomId}/questions`,
    questionsAsk: (roomId: string) => `/meetings/rooms/${roomId}/questions`,
    questionsUpvote: (roomId: string, questionId: string) => `/meetings/rooms/${roomId}/questions/${questionId}/upvote`,
    questionsAnswer: (roomId: string, questionId: string) => `/meetings/rooms/${roomId}/questions/${questionId}/answer`,
    breakoutsStart: (roomId: string) => `/meetings/rooms/${roomId}/breakouts`,
    breakoutsEnd: (roomId: string) => `/meetings/rooms/${roomId}/breakouts/end`,
    breakoutsMyAssignment: (roomId: string) => `/meetings/rooms/${roomId}/breakouts/my-assignment`,
  },
  workspaces: {
    base: "/workspaces",
    list: "/workspaces",
    get: (id: string) => `/workspaces/${id}`,
    select: (id: string) => `/workspaces/${id}/select`,
    settings: (id: string) => `/workspaces/${id}/settings`,
    members: (workspaceId: string) => `/workspaces/${workspaceId}/members`,
    memberDetail: (workspaceId: string, userId: string) => `/workspaces/${workspaceId}/members/${userId}`,
    memberRole: (workspaceId: string, userId: string) => `/workspaces/${workspaceId}/members/${userId}/role`,
    memberRoleChangePreview: (workspaceId: string, userId: string) => `/workspaces/${workspaceId}/members/${userId}/role-change-preview`,
    memberRoleChange: (workspaceId: string, userId: string) => `/workspaces/${workspaceId}/members/${userId}/role-change`,
    transferOwnership: (workspaceId: string) => `/workspaces/${workspaceId}/members/transfer-ownership`,
    invitations: (workspaceId: string) => `/workspaces/${workspaceId}/invitations`,
    retryInvitation: (workspaceId: string, inviteId: string) => `/workspaces/${workspaceId}/invitations/${inviteId}/retry-delivery`,
    revokeInvitation: (workspaceId: string, inviteId: string) => `/workspaces/${workspaceId}/invitations/${inviteId}`,
    previewInvitation: (token: string) => `/workspaces/invitations/preview?token=${encodeURIComponent(token)}`,
    pendingInvitations: "/workspaces/invitations/pending",
    acceptInvitation: "/workspaces/invitations/accept",
    acceptInvitationById: (inviteId: string) => `/workspaces/invitations/${inviteId}/accept`,
    joinRequests: "/workspaces/join-requests",
    approveJoinRequest: (workspaceId: string, inviteId: string) => `/workspaces/${workspaceId}/join-requests/${inviteId}/approve`,
    rejectJoinRequest: (workspaceId: string, inviteId: string) => `/workspaces/${workspaceId}/join-requests/${inviteId}/reject`,
    documents: (workspaceId: string) => `/workspaces/${workspaceId}/documents`,
    knowledge: (workspaceId: string) => `/workspaces/${workspaceId}/knowledge`,
    documentDetail: (workspaceId: string, docId: string) => `/workspaces/${workspaceId}/documents/${docId}`,
    documentExtractedText: (workspaceId: string, docId: string) => `/workspaces/${workspaceId}/documents/${docId}/extracted-text`,
    documentApprove: (workspaceId: string, docId: string) => `/workspaces/${workspaceId}/documents/${docId}/approve`,
    documentDownload: (workspaceId: string, docId: string) => `/workspaces/${workspaceId}/documents/${docId}/download`,
    documentPolicies: (workspaceId: string, docId: string) => `/workspaces/${workspaceId}/documents/${docId}/policies`,
    documentPolicyDetail: (workspaceId: string, docId: string, policyId: string) => `/workspaces/${workspaceId}/documents/${docId}/policies/${policyId}`,
  },
  glossaries: {
    base: "/glossaries",
    get: (id: string) => `/glossaries/${id}`,
    byWorkspace: (workspaceId: string) => `/glossaries/workspace/${workspaceId}`,
    terms: (id: string) => `/glossaries/${id}/terms`,
    termDetail: (id: string, termId: string) => `/glossaries/${id}/terms/${termId}`,
    global: "/glossaries/global",
  },
  assistant: {
    conversations: "/assistant/conversations",
    conversation: (id: string) => `/assistant/conversations/${id}`,
    sendMessage: (id: string) => `/assistant/conversations/${id}/messages`,
    skills: "/assistant/skills",
  },
  adminWorkspaces: {
    base: "/admin/workspaces",
    detail: (id: string) => `/admin/workspaces/${id}`,
    suspend: (id: string) => `/admin/workspaces/${id}/suspend`,
    reactivate: (id: string) => `/admin/workspaces/${id}/reactivate`,
    // Separate from `workspaces.knowledge` on purpose: same page shape, different
    // authorization. This one is gated by the platform "admin" role and reads a workspace
    // the caller is not a member of.
    knowledge: (id: string) => `/admin/workspaces/${id}/knowledge`,
  },
  adminGlobalGlossary: {
    base: "/admin/global-glossary",
    detail: (id: string) => `/admin/global-glossary/${id}`,
    publish: (id: string) => `/admin/global-glossary/${id}/publish`,
    archive: (id: string) => `/admin/global-glossary/${id}/archive`,
    bulkImport: "/admin/global-glossary/bulk-import",
    audits: (id: string) => `/admin/global-glossary/${id}/audits`,
  },
} as const;
