import { Download, FileText, ListChecks, MessageSquareText, ScrollText } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

const artifacts = [
  { title: "Final transcript", detail: "124 segments - English, Vietnamese, Japanese", icon: ScrollText },
  { title: "AI meeting summary", detail: "Key points, risks, follow-ups", icon: MessageSquareText },
  { title: "Action items", detail: "6 tasks extracted from transcript", icon: ListChecks },
  { title: "Export package", detail: "PDF, DOCX, VTT preview", icon: FileText },
];

export default function RoomArtifactsPage() {
  return (
    <div className="grid gap-4">
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <p className="text-xs font-medium uppercase tracking-wide text-neutral-500">Post-meeting artifacts</p>
          <h1 className="text-2xl font-semibold tracking-tight">Board Review Translation</h1>
          <p className="text-sm text-neutral-500">Review transcript, summary, action items, and export-ready files.</p>
        </div>
        <Badge variant="outline">Ready preview</Badge>
      </div>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        {artifacts.map((artifact) => (
          <Card key={artifact.title}>
            <CardContent className="p-4">
              <artifact.icon className="mb-4 h-5 w-5 text-neutral-950" />
              <p className="font-medium">{artifact.title}</p>
              <p className="mt-1 text-sm text-neutral-500">{artifact.detail}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_360px]">
        <Card>
          <CardHeader>
            <CardTitle>AI summary draft</CardTitle>
            <CardDescription>Generated by the AI assistant worker after room completion.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4 text-sm text-neutral-600">
            <p>The meeting focused on rollout readiness, investor Q&A preparation, and terminology cleanup before the next customer review.</p>
            <div className="rounded-2xl border bg-white p-4">
              <p className="font-medium text-neutral-950">Decisions</p>
              <ul className="mt-2 list-disc space-y-1 pl-5">
                <li>Publish Vietnamese glossary updates before the next session.</li>
                <li>Route low-confidence segments to manager review.</li>
                <li>Share action items with the workspace owner.</li>
              </ul>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Exports</CardTitle>
            <CardDescription>Visual preview until artifact URLs are available.</CardDescription>
          </CardHeader>
          <CardContent className="grid gap-2">
            {["PDF summary", "DOCX report", "VTT captions", "Transcript TXT"].map((item) => (
              <Button key={item} variant="outline" className="justify-between rounded-full">
                {item}
                <Download className="h-4 w-4" />
              </Button>
            ))}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
