export default function AiSummariesPage() {
  return (
    <div className="space-y-6 h-full flex flex-col">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">AI Summaries & Notes</h1>
        <p className="text-muted-foreground">
          View automated meeting summaries and action items generated by AI.
        </p>
      </div>
      
      <div className="flex-1 border rounded-lg flex items-center justify-center bg-muted/20">
        <div className="text-center max-w-md">
          <h3 className="text-lg font-medium">No Summaries Yet</h3>
          <p className="text-sm text-muted-foreground mt-2">
            Host a meeting and use the AI Assistant to generate a summary. The results will appear here.
          </p>
        </div>
      </div>
    </div>
  );
}
